package org.ruru.ffta2editor.model.job;

import java.util.List;
import java.util.stream.IntStream;

import org.ruru.ffta2editor.App;

public class JobId {
    
    public short id;
    public String name;

    public JobId(short id, String name) {
        this.id = id;
        this.name = name;
    }

    public String toString() {
        return name;
    }

    public static String[] jobNames = {
        "",
        "Soldier",
        "Thief",
        "White Mage",
        "Black Mage",
        "Archer",
        "Paladin",
        "Fighter",
        "Parivir",
        "Ninja",
        "Illusionist",
        "Blue Mage",
        "Hunter",
        "Seer",
        "Warrior",
        "White Monk",
        "Dragoon",
        "Defender",
        "Gladiator",
        "Master Monk",
        "Bishop",
        "Templar",
        "Cannoneer",
        "Trickster",
        "White Mage",
        "Black Mage",
        "Beastmaster",
        "Time Mage",
        "Illusionist",
        "Alchemist",
        "Arcanist",
        "Sage",
        "Scholar",
        "Keeper",
        "Fencer",
        "White Mage",
        "Green Mage",
        "Archer",
        "Elementalist",
        "Red Mage",
        "Spellblade",
        "Summoner",
        "Assassin",
        "Sniper",
        "Animist",
        "Thief",
        "Black Mage",
        "Moogle Knight",
        "Fusilier",
        "Juggler",
        "Tinker",
        "Time Mage",
        "Chocobo Knight",
        "Flintlock",
        "Berserker",
        "Ranger",
        "Lanista",
        "Viking",
        "Hunter",
        "Raptor",
        "Ravager",
        "Geomancer",
        "Baknamy",
        "Luchorpan",
        "Sprite",
        "Banshee",
        "Lamia",
        "Lilith",
        "Lamashtu",
        "Wolf",
        "Worgen",
        "Hellhound",
        "Dreamhare",
        "Hoppy Bunny",
        "Werewolf",
        "Zaghnal",
        "Loup-garou",
        "Antlion",
        "Pit Beast",
        "Great Tortoise",
        "Rocktitan",
        "Adamantitan",
        "Toughskin",
        "Malboro",
        "Great Malboro",
        "Malboro King",
        "Cassie",
        "Alraune",
        "Deadly Nightshade",
        "Cockatrice",
        "Axebeak",
        "Cluckatrice",
        "Chocobo",
        "Red Chocobo",
        "Black Chocobo",
        "Green Chocobo",
        "Brown Chocobo",
        "White Chocobo",
        "Red Marshmallow",
        "Yellow Jelly",
        "Ice Flan",
        "White Pudding",
        "Bomb",
        "Grenade",
        "Zombie",
        "Ghoul",
        "Ghost",
        "Wraith",
        "Deathscythe",
        "Oversoul",
        "Floating Eye",
        "Bloody Orb",
        "Ahriman",
        "Plague",
        "Tonberry",
        "Tonberry King",
        "Headless",
        "Wendigo",
        "Golem",
        "Behemoth",
        "Reaver",
        "Magick Pot",
        "Fire Drake",
        "Ice Drake",
        "Thunder Drake",
        "Nagaraja",
        "Nidhogg",
        "Zahak",
        "Mimic",
        "Mooglebane",
        "Yowie",
        "Rafflesia",
        "Demon Wall",
        "Neukhia",
        "Neukhia Pod",
        "Crushatrice",
        "Upsilon",
        "Neukhia Core",
        "Neukhia Wisp",
        "NOT USED",
        "-",
        "Sky Pirate",
        "Dancer",
        "Bard",
        "Heritor",
        "Agent",
        "Nightshade",
        "Gimmick Unit",
        "Gimmick Unit",
        "Gimmick Unit",
        "Gimmick Unit",
        "Gimmick Unit",
        "Gimmick Unit",
        "Gimmick Unit",
        "-",
        "Moogletron",
        "Gimmick Unit",
        "Rider",
        "Red Rider",
        "Black Rider",
        "Green Rider",
        "Brown Rider",
        "White Rider",
    };

    //public static List<String> nameWithIndex = IntStream.range(0, App.jobNames.size()).mapToObj(i -> String.format("%X: %s", i, App.jobNames.get(i))).toList();
}
